version: '3'

services:
  nginx_proxy:
    image: nginxinc/nginx-unprivileged:stable-alpine-slim
    container_name: nginx_proxy
    hostname: nginx_proxy
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: "Europe/Moscow"
      
  nginx_web_1:
    image: nginxinc/nginx-unprivileged:stable-alpine-slim
    container_name: nginx_web_1
    hostname: nginx_web_1
    restart: unless-stopped
    volumes:
      - ./nginx/web-1/nginx.conf:/etc/nginx/nginx.conf
    environment:
        TZ: "Europe/Moscow"
       
  nginx_web_2:
    image: nginxinc/nginx-unprivileged:stable-alpine-slim
    container_name: nginx_web_2
    hostname: nginx_web_2
    restart: unless-stopped
    volumes:
      - ./nginx/web-2/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: "Europe/Moscow"
